name: ml_reprod_hybrid_energy_models
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.7
  - pytorch=1.6.0
  - torchvision=0.7.0=py37_cpu
  - tqdm=4.47.0
  - pip
  - pip:
      - replicate